baseURL = "https://qualgo.github.io"
languageCode = "en-us"
title = "Qualgo"
theme = "company"
disableKinds = [ "taxonomy", "taxonomyTerm" ]

[markup.goldmark.renderer]
unsafe = true

[params]
openGraph = true

[params.navbarlogo]
image = "logos/qualgo.png"
width = 91.81
link = "/#"

[params.font]
name = "Open Sans"
sizes = [ 400, 600 ]

[params.hero]
title = "Quality you can depend on"
subtitle = "At Qualgo we take full responsibility in delivering quality applications with every line of code that is committed and deployed."
buttontext = "Our Mission"
buttonlink = "#mission"
image = "illustrations/programmer.png"

[[params.navbar]]
title = "Our Mission"
url = "/#mission"

[[params.navbar]]
title = "Our Services"
url = "/#services"

[[params.navbar]]
title = "About us"
url = "/#about-us"

[[params.navbar]]
title = "Contact us"
url = "/#contact-us"

[params.section1]
title = "Our Services"
subtitle = "With great power comes great responsibility"

[[params.section1.tiles]]
title = "App builder"
icon = "mouse-globe"
text = "This is some explanatory text that is on two rows"
url = "/"
buttonText = "Free trial"

[params.section2]
title = "Our Mission"
subtitle = "You're here because you want the best and we know it"

[[params.section2.features]]
title = "Powerful and unified interface"
text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis."
icon = "laptop-globe"

[[params.section2.features]]
title = "Cross-device synchronisation"
text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis."
icon = "doc-sync"

[[params.section2.features]]
title = "Nomad system"
text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis."
icon = "mobile-feed"

[[params.section1.tiles]]
title = "Cloud integration"
icon = "laptop-cloud"
text = "This is some explanatory text that is on two rows"
url = "/"
buttonText = "Get started"

[[params.section1.tiles]]
title = "Add-ons & plugins"
icon = "plug-cloud"
text = "This is some explanatory text that is on two rows"
url = "/"
buttonText = "Get started"

[params.section4]
title = "About us"
subtitle = "Lorem ipsum sit dolor amet is a dummy text used by typography industry"

[[params.section4.clients]]
name = "Irma Walters"
quote = "Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at."
job = "Accountant"
img = 1

[[params.section4.clients]]
name = "John Bradley"
quote = "Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at."
job = "Financial Analyst"
img = 2

[[params.section4.clients]]
name = "Gary Blackman"
quote = "Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at."
job = "HR Manager"
img = 3

[params.section5]
title = "Contact us"
subtitle = "We'd love to hear from you"

[params.footer]
logo = "qualgo.png"
socialmediatitle = "Follow Us"

[[params.footer.socialmedia]]
link = "https://github.com/Qualgo"
icon = "github"

[[params.footer.socialmedia]]
link = "https://www.linkedin.com/company/qualgo-io/"
icon = "linkedin"
