baseURL = "https://qualgo.github.io"
languageCode = "en-us"
title = "Qualgo"
theme = "company"
disableKinds = [ "taxonomy", "taxonomyTerm" ]

[markup.goldmark.renderer]
unsafe = true

[params]
openGraph = true

[params.navbarlogo]
image = "logos/qualgo.png"
width = 91.81
link = "/#"

[params.font]
name = "Open Sans"
sizes = [ 400, 600 ]

[params.hero]
title = "Quality you can depend on"
subtitle = "At Qualgo we take full responsibility in delivering quality applications with every line of code that is committed and deployed."
buttontext = "Our Mission"
buttonlink = "#section_mission"
image = "illustrations/icons/startup.svg"

[[params.navbar]]
title = "Our Mission"
url = "/#section_mission"

[[params.navbar]]
title = "About us"
url = "/#about-us"

[[params.navbar]]
title = "Our Services"
url = "/#services"

[[params.navbar]]
title = "Contact us"
url = "/#contact-us"

[params.section_mission]
title = "Our Mission"
subtitle = "Quality Algorithms"

[[params.section_mission.features]]
title = "Building better technology always wins"
text = "We founded the company on one simple premise: <i>building better technology always wins and cutting-corners always loses</i>. In order to be successful, customer expectations must be delivered without ever compromising on high quality standards."
icon = "team-coding"

[[params.section_mission.features]]
title = "Delivering on customer expectations"
text = "High quality implies that our code is well tested and bug free, respects web development standards (W3C Standards), respects web security standards (NIST), is able to scale to serve millions of users, is deployed in a cost-effective manner that aims to maximize customer profits, and ultimately delivers on customer expectations."
icon = "developer-desk"

[[params.section_mission.features]]
title = "Qualgo"
text = "<b>Qu</b>ality <b>Algo</b>rithms you can depend on: we take full responsibility in <i>delivering quality applications with every line of code that is committed and deployed</i>."
icon = "product-launch"

[params.section_services]
title = "Our Services"
subtitle = "End-to-End Software Development Solutions"

[[params.section_services.tiles]]
title = "Web applications"
icon = "designing-website"
text = "Web applications"
url = "/"
buttonText = "Free trial"

[[params.section_services.tiles]]
title = "Mobile applications"
icon = "mobile"
text = "Mobile applications"
url = "/"
buttonText = "Get started"

[[params.section_services.tiles]]
title = "Saas products"
icon = "data-cloud"
text = "Saas products"
url = "/"
buttonText = "Get started"

[params.section_about_us]
title = "About us"
subtitle = "Meet the Qualgo team"

[[params.section_about_us.clients]]
name = "Razine Bensari"
quote = "Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at."
job = "Backend Engineer"
img = 1

[[params.section_about_us.clients]]
name = "Marwan Awadi"
quote = "Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at."
job = "Frontend Engineer & UI/UX Designer"
img = 2

[[params.section_about_us.clients]]
name = "Abdulrahim Mansour"
quote = "Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at."
job = "Full Stack Developer"
img = 3

[params.section_contact_us]
title = "Contact us"
subtitle = "We'd love to hear from you"

[params.footer]
logo = "qualgo.png"
socialmediatitle = "Follow Us"

[[params.footer.socialmedia]]
link = "https://github.com/Qualgo"
icon = "github"

[[params.footer.socialmedia]]
link = "https://www.linkedin.com/company/qualgo-io/"
icon = "linkedin"
